config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'

  get 'about', to: 'home#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  has_attached_file :image,
                    styles: {
                              medium: "300x300>",
                              thumb: "100x100>"
                            }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user = current_user  # fixes "user must exist" error

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id:params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/about.html.erb
<div class="row pt-3">
  <div class="col text-center">
    <h1>About</h1>
  </div>
</div>
<div class="row pt-3">
  <div class="col">
    <p>Hi, I'm Bianca. As a practice project during my time learning Rails at <a href="https://coderacademy.edu.au/">Coder Academy's</a> fast track bootcamp, I built this website. You might notice it bears some similarity to Pinterest, but this one is all about interesting pins... of all kinds!</p>
    <p>You can find more of my work over at <a href="https://github.com/biancapower/">GitHub</a> (although that's probably where you found this in the first place).</p>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron bg-dark text-white">
  <h1>Welcome to Pinteresting</h1>

  <p>Are you Pinterested?</p>

  <%= link_to 'About Us', about_path, class: 'btn btn-info' %>
  <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinteresting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <div class="container">

      <!-- <p class="alert alert-primary"><%#= notice %></p>
      <p class="alert alert-success"><%#= alert %></p> -->
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <div class="container pt-2 pb-2">
    <%= link_to 'Pinteresting', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li>
          <%= link_to(new_pin_path, class: "nav-link") do %>
            Add&nbsp;Pin
          <% end %>
        </li>
        <li>
          <%= link_to(edit_user_registration_path, class: "nav-link") do %>
            My&nbsp;Account
          <% end %>
        </li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <li><%= link_to "Join", new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :pin_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
</div>

<div class="row">
  <% @pins.each do |pin| %>

    <div class="col">
      <div class="card m-5 border-dark">

        <div class="card-body image-cropper text-center">
          <%= link_to image_tag(pin.image.url(:medium), class: "pin-image"), pin %>
        </div>

        <div class="card-footer bg-dark text-white text-center">
          <%= pin.description %>
        </div>

      </div>
    </div>


  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
</div>

<div class="row">

  <div class="col">
      <div class="row">
        <div class="col text-center">
          <%= image_tag @pin.image.url(:medium) %>
        </div>
      </div>
      <div class="row">
        <div class="col text-center bg-dark p-3 text-white mt-5">
          <%= @pin.description %>
        </div>
      </div>
    </div>
  </div>

</div>

<div class="row mt-5">
  <div class="col text-center">
    <% if @pin.user == current_user %>
      <%= link_to 'Edit', edit_pin_path(@pin) %> |
      <%= link_to 'Destroy', @pin, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>
    <%= link_to 'Back', pins_path, class: "btn btn-dark" %>
  </div>
</div>